name: Release Extension

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Setup Deno
        # You may pin to the exact commit or the version.
        # uses: denoland/setup-deno@4606d5cc6fb3f673efd4f594850e3f4b3e9d29cd
        uses: denoland/setup-deno@v2.0.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Zip extensions
        run: pnpm build:ext

      - name: Submit to stores
        run: |
          pnpm wxt submit \
            --chrome-zip .output/*-chrome.zip \
        env:
          CHROME_EXTENSION_ID: ${{ vars.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
